version: 0.0
os: linux
files:
  - source: . # 指定 github repo 底下所有檔案
    destination: /home/ec2-user/be_line_cocial_crm # 把所有檔案複製到指定資料夾
file_exists_behavior: OVERWRITE # 覆蓋已有檔案
permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user
hooks:
  ApplicationStart:
    - location: deploy.sh
      timeout: 300
      runas: ec2-user